//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 템플릿에서 생성되었습니다.
//
//     이 파일을 수동으로 변경하면 응용 프로그램에서 예기치 않은 동작이 발생할 수 있습니다.
//     이 파일을 수동으로 변경하면 코드가 다시 생성될 때 변경 내용을 덮어씁니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Employee()
        {
            this.Img = new HashSet<Img>();
        }
    
        public int employeeId { get; set; }
        public string employeeCode { get; set; }
        public string loginId { get; set; }
        public string passwd { get; set; }
        public string messId { get; set; }
        public string phone { get; set; }
        public string employeeName { get; set; }
        public string email { get; set; }
        public Nullable<int> gender { get; set; }
        public string employeeType { get; set; }
        public string employeeRank { get; set; }
        public string memo { get; set; }
        public int departmentId { get; set; }
        public Nullable<int> subDeptId { get; set; }
    
        public virtual Department Department { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Img> Img { get; set; }
        public virtual SubDepartment SubDepartment { get; set; }
    }
}
