//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 템플릿에서 생성되었습니다.
//
//     이 파일을 수동으로 변경하면 응용 프로그램에서 예기치 않은 동작이 발생할 수 있습니다.
//     이 파일을 수동으로 변경하면 코드가 다시 생성될 때 변경 내용을 덮어씁니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public int employeeId { get; set; }
        public string employeeCode { get; set; }
        public string loginId { get; set; }
        public string passwd { get; set; }
        public string messId { get; set; }
        public string phone { get; set; }
        public string employeeName { get; set; }
        public string email { get; set; }
        public Nullable<int> gender { get; set; }
        public string employeeType { get; set; }
        public string employeeRank { get; set; }
        public string memo { get; set; }
        public int departmentId { get; set; }
        public Nullable<int> imgId { get; set; }
    
        public virtual Department Department { get; set; }
        public virtual img img { get; set; }
    }
}
